Be-Secure/BeSLighthouse

mkdocs.yml
Took out the visualisation tab as it is not necessary.
=> Took out visualisation tab

README.md, bes_theme/BesRepoViz.html, bes_theme/overrides/home.html
=> Fixed Issue#9

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/new_oss.yml, README.md, references.md
This pull request resolves issue #31
=> Added template for tracking oss projects

.github/ISSUE_TEMPLATE/new_oss.yml
Added GPL-2.0 license into the issue template
=> Added GPL2.0 license

.github/ISSUE_TEMPLATE/new_os_tracking_request.yml
=> Fixed Issue #54

bes_theme/BesRepoViz.html, bes_theme/assets/javascripts/run.js
=> Fixed issue #98

bes_theme/assets/data/OSSP-master.js
- Fixed issue #96 
- Added details for drupal under ossp-master
=> Fixed issue #96 & Added CVE details for drupal

README.md, bes_theme/BesRepoViz.html, bes_theme/assets/javascripts/run.js, mkdocs.yml
=> Added base_url var for path ref

bes_theme/overrides/home.html
=> Fixed issue #302

bes_theme/assets/javascripts/version_summary.js
=> updated veriosn details

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/377-level-zero-Versiondetails.json
=> Added intel project level-zero

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/378-level-zero-spec-Versiondetails.json
=> Added intel project level-zero-spec

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/379-unified-runtime-Versiondetails.json
=> Added intel project unified-runtime

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/380-visual-quality-inspection-Versiondetails.json
=> Added intel project  visual-quality-inspection

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/289-logstash-Versiondetails.json, bes_theme/assets/data/version_details/290-struts-Versiondetails.json, bes_theme/assets/data/version_details/292-ThreatPlaybook-Versiondetails.json, bes_theme/assets/data/version_details/343-gramine-Versiondetails.json
=> Ossp master update for gramine, logstash, threatplaybook, struts

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/275-scikit-learn-Versiondetails.json
=> Added details for scikit-learn

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/291-primeng-Versiondetails.json, bes_theme/assets/data/version_details/293-toit-Versiondetails.json, bes_theme/assets/data/version_details/294-spiderfoot-Versiondetails.json
[#294](https://github.com/Be-Secure/BeSLighthouse/issues/294)[#293](https://github.com/Be-Secure/BeSLighthouse/issues/293)[#291](uhttps://github.com/Be-Secure/BeSLighthouse/issues/291)
=> Updating versiondetails and OSSPmasterdetails for spiderfoot,toit and primeng

bes_theme/assets/data/version_details/160-canvas-lms-Versiondetails.json
#160 cnavas lms change the name of  version detils tag in
=> update version tag for canvas-lms

bes_theme/assets/data/version_details/311-owlviewer-Versiondetails.json, bes_theme/assets/data/version_details/312-security-analytics-export-tools-Versiondetails.json, bes_theme/assets/javascripts/project_of_interest.js, bes_theme/assets/javascripts/version_summary.js, bes_theme/style.css
=> Fixed issue #397 #325 #324

bes_theme/assets/javascripts/project_of_interest.js, bes_theme/projectOfInterest.html, bes_theme/style.css
=> Fixed #406

bes_theme/assets/data/OSSP-master.js, bes_theme/assets/data/version_details/148-koha-Versiondetails.json, bes_theme/assets/data/version_details/195-espocrm-Versiondetails.json, bes_theme/assets/data/version_details/197-bit-Versiondetails.json, bes_theme/assets/data/version_details/198-joplin-Versiondetails.json, bes_theme/assets/data/version_details/242-hexo-Versiondetails.json
hexo: https://github.com/Be-Secure/Be-Secure/issues/242
joplin: https://github.com/Be-Secure/Be-Secure/issues/198
=> hexo, jopllin version details updated

bes_theme/assets/data/OSSP-master.js
bit : https://github.com/Be-Secure/Be-Secure/issues/197
Koha: https://github.com/Be-Secure/Be-Secure/issues/148
espocrm: https://github.com/Be-Secure/Be-Secure/issues/195
=> added bit, Koha, espocrm to OSSP-master & added version details

bes_theme/assets/data/version_details/234-struts-Versiondetails.json, bes_theme/assets/data/version_details/235-logstash-Versiondetails.json, bes_theme/assets/data/version_details/82-gramine-Versiondetails.json
[struts#234](https://github.com/Be-Secure/Be-Secure/issues/234)
[logstash#235](https://github.com/Be-Secure/Be-Secure/issues/235)
[gramine#82](https://github.com/Be-Secure/Be-Secure/issues/82)
=> updating version number in version details of struts, logstash, gramine

bes_theme/assets/javascripts/assessment_reports.js, bes_theme/assets/javascripts/version_summary.js
=> Added visualisation for license compliance

bes_theme/assets/javascripts/assessment_reports.js, bes_theme/assets/javascripts/version_summary.js
added code to assessment_report.js & version_summary.js
https://github.com/Be-Secure/BeSLighthouse/issues/433
=> added sbom visualization code

bes_theme/assets/javascripts/version_summary.js
=> Fixed #438

src/pages/Presentation/index.tsx
**List of changes:**
1. Changed the purple color graphics in the landing page to a gradient similar to BeSecure community site home page.
2. Removed the BeSLighthouse text & logo from the landing page.
3. Added marketing text to left on the landing page.
4. Added TRY IT button.
=> Updated Landing page UI

discussion.md
Community discussion notes update
=> Community discussion notes update

src/pages/FuzzingModel/AttackType/AttackVulnerabilityReport.tsx, src/pages/FuzzingModel/AttackType/ModelAttack.tsx, src/pages/FuzzingModel/DefenceData.tsx, src/pages/FuzzingModel/index.tsx, src/pages/FuzzingModel/sections/DefenseSummary.tsx, src/pages/FuzzingModel/sections/LeftFuzzing.tsx, src/pages/FuzzingModel/sections/RightFuzzing.tsx
=> Attack Graph Emulation revamp

src/pages/BesVersionHistory/AssessmentAnalytics/index.tsx, src/pages/BesVersionHistory/AssessmentReport/index.tsx
Modified name and No data messages
=> Updated project assessment summary UI and no data cases

src/pages/ModelOfInterest/ModelDisplay/ModelTable.tsx
=> Updates to the Models table

src/pages/ModelVulnerabilitiesDetailed/ModelVulnerabilitiesDetailedTable.tsx
Detailed weakness report changes
=> Detailed weakness report changes

src/pages/BesVersionHistory/AssessmentReport/index.tsx, src/pages/FuzzingModel/DefenceData.tsx, src/pages/FuzzingModel/sections/DefenseSummary.tsx, src/utils/fatch_json_report.ts
=> Added Two download buttons in Defence and vulnerability report

src/pages/ModelOfInterest/GraphDisplay/index.tsx
https://github.com/Be-Secure/BeSLighthouse/issues/509 
1. Reduced node size.
2. Changed model node color (black and orange).
3. Improved graph UI by adding force between the node.
Fixed Bugs: https://github.com/Be-Secure/BeSLighthouse/issues/507 https://github.com/Be-Secure/BeSLighthouse/issues/506
=> Updated Graph UI

src/pages/FuzzingModel/index.tsx, src/pages/FuzzingModel/sections/LeftFuzzing.tsx, src/pages/FuzzingModel/sections/RightFuzzing.tsx, src/pages/ModelVulnerabilitiesDetailed/index.tsx, src/pages/ShowModelDetails/StaticAnalysisSummary.tsx
- Fix #522
- Fix #524 
- Fix #525 
- Corrected attribution images.
=> Fixed #522, #524, #525

src/pages/ModelOfInterest/GraphDisplay/index.tsx
https://github.com/Be-Secure/BeSLighthouse/issues/523
1. Added clickable text.
2. Added color code indicator.
=> Graph update in MOI

src/pages/BesVersionHistory/AssessmentReport/index.tsx, src/pages/BesVersionHistory/index.tsx
=> Fixed #534 #537 #539

src/pages/BesVersionHistory/AssessmentReport/FetchSastReport.tsx, src/pages/BesVersionHistory/AssessmentReport/SastToggleButton.tsx, src/pages/BesVersionHistory/AssessmentReport/index.tsx, src/pages/BesVersionHistory/index.tsx
- Fix #540 
- Added toggle button to switch sast reports
=> Fixed issue #540

src/pages/ModelOfInterest/GraphDisplay/index.tsx
https://github.com/Be-Secure/BeSLighthouse/issues/550
=> Fixed graph view button issue

src/pages/BesVersionHistory/index.tsx, src/utils/fatch_json_report.ts
Fixed 
https://github.com/Be-Secure/BeSLighthouse/issues/545 
https://github.com/Be-Secure/BeSLighthouse/issues/553 
1. Added sanity check code for BeS Environment link in POI project card.
2. Fixed redirecting to invalid BeS env link for jackson-databind.
=> Added sanity check on link to BeS environment scripts in POI project card 

LICENSE.txt, README.md
1. Updated the readme.md with more details on the Getting Started guide
2. Added the LICENSE.txt file
=> Readme file update and license added

src/routes.tsx
=> Fixed #558

src/pages/BesVersionHistory/AssessmentReport/SastToggleButton.tsx
=> Fixed #562

src/pages/BesVersionHistory/AssessmentReport/index.tsx
=> Fixed #541

src/pages/BesVersionHistory/AssessmentAnalytics/index.tsx, src/pages/BesVersionHistory/AssessmentReport/index.tsx
=> Fixed #567 #542

src/examples/Charts/BarChart/VulHistory/index.tsx, src/pages/BesVersionHistory/AssessmentAnalytics/index.tsx, src/pages/BesVersionHistory/index.tsx
The OSAR and Envs & playbook button has been disabled, as we dont have the data for it
=> Disabled OSAR,envs & playbook button ; Adjusted height of charts

src/pages/BesVersionHistory/AssessmentReport/index.tsx, src/pages/BesVersionHistory/index.tsx
=> Fix count for SonarQube data

src/pages/BesVersionHistory/AssessmentReport/BasicTable.tsx, src/pages/BesVersionHistory/AssessmentReport/index.tsx
=> Fixed #594 : Adjusted css for scorecard summary card

src/pages/BesAssessmentReport/CodeQL/index.tsx, src/pages/BesVersionHistory/AssessmentAnalytics/index.tsx, src/pages/BesVersionHistory/AssessmentReport/BasicTable.tsx, src/pages/BesVersionHistory/AssessmentReport/FetchSastReport.tsx, src/pages/BesVersionHistory/AssessmentReport/SastToggleButton.tsx, src/pages/BesVersionHistory/AssessmentReport/index.tsx, src/pages/BesVersionHistory/index.tsx
=> Added SAST vulnerability - msg label

src/dataStore.ts, src/pages/BesVersionHistory/AssessmentReport/index.tsx
https://github.com/Be-Secure/BeSLighthouse/issues/599
Added info icon for OpenSSF Scorecard and criticality score to provide risk score grading.
=> Added info icon for OpenSSF Scorecard and criticality score

src/pages/BesVersionHistory/AssessmentReport/index.tsx
=> Fixed #600 : Added info on dependency's weakness availability under dependency summary card  

src/pages/BesVersionHistory/AssessmentReport/index.tsx
https://github.com/Be-Secure/BeSLighthouse/issues/607
1. Added round corners for each card.
2. Added a close button for project cards.
3. Changed text from "Click to get the detailed report" to "Detailed Report".
4. Updated OpenSSF Criticality Score info.
5. Added OpenSSF Criticality Score and Scorecard definition in info.
=> Improved UI

beslighthouse.service, beslighthouse.sh
=> added service files

beslighthouse.sh
=> update check in service script

beslighthouse.service
=> Changed bin to lib

.github/workflows/publish.yml, src/apiDetailsConfig.json, src/components/Navbars/DefaultNavbar/index.tsx, src/pages/BesVersionHistory/index.tsx, src/pages/ShowModelDetails/AdversarialAttackSummary.tsx
=> Update develop branch

package.json, src/pages/BesVersionHistory/index.tsx
OSAR link fix and default port to be 80
=> OSAR link fix

.env, src/pages/ShowModelDetails/SpearPhishingModalDetails.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx
=> Fixed #667: Summary page for spear phishing benchmark test

src/apiDetailsConfig.json, src/components/ModelReport/ModelCardDetails.tsx, src/pages/ShowModelDetails/MitreModal.tsx, src/pages/ShowModelDetails/SpearPhishingModalDetails.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx
* Fix modal Card for spear Phishing
=> Responsive UI for Mitre and Spear Phishing(#671)

src/apiDetailsConfig.json, src/pages/ShowModelDetails/AutocompleteModalDetails.tsx, src/pages/ShowModelDetails/PromptInjectionModal.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx
=> Fixed #675; #674: Summary card for autocomplete and instruct benchmark test

src/apiDetailsConfig.json, src/pages/ShowModelDetails/AutocompleteModalDetails.tsx, src/pages/ShowModelDetails/PromptInjectionModal.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx
Added the following benchmark test summary cards,
- Prompt injection
- Autocomplete
- Instruct
=> Syncing changes with main for release 0.25.0

src/pages/ShowModelDetails/MitreModal.tsx
* Fix order of Attack Categories
=> Fix order of Attack Categories (#684)

src/pages/ShowModelDetails/SpearPhishingModalDetails.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx
Fix: https://github.com/Be-Secure/BeSLighthouse/issues/694
=> Fix granite-code model page is not rendering

src/apiDetailsConfig.json, src/pages/ShowModelDetails/index.tsx
=> Fix model view (#704)

src/pages/ShowModelDetails/AutocompleteModalDetails.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx
=> Added Safety Benchmark and Security Benchmark

src/pages/ShowModelDetails/AutocompleteModalDetails.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx
* Added Safety Benchmark and Security Benchmark
* Fix css for table
* Added Security Benchmark->vulnerability analysis
=> Added Safety Benchmark and Security Benchmark (#706)

src/apiDetailsConfig.json, src/pages/ShowModelDetails/SummaryDashboard.tsx
* Vulnerability analysis ->LLM Robustness Audit
* version bump
=> Vulnerability analysis ->LLM Robustness Audit (#709)

src/pages/ProjectOfInterest/filter/references.ts
* Fix Industry tag
* remove debugger
=> Fix Industry tag (#714)

src/apiDetailsConfig.json, src/pages/BesVersionHistory/AssessmentReport/index.tsx, src/pages/BesVersionHistory/index.tsx
* Fix pagination and hover over feature for bubbles chart
* Fix bubble and pie chart
=> Fix pagination and hover over feature for bubbles chart (#716)

src/apiDetailsConfig.json, src/components/ModelReport/AttackSummary.tsx, src/components/ModelReport/InsecureCodeDetection.tsx, src/components/ModelReport/OSAR.tsx, src/dataStore.ts, src/pages/BesVersionHistory/AssessmentReport/index.tsx, src/pages/ShowModelDetails/SummaryDashboard.tsx, src/pages/VulnerabilityOfInterest/index.tsx, src/utils/fatchJsonReport.ts, src/utils/sortFilter.ts
* Fix GitLab issue
* version bump
=> GitLab Private and public api support (#721)
